### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [appc/acpush#3]
```
# github.com/appc/acpush/lib
gopath/src/github.com/appc/acpush/lib/lib.go:26: imported and not used: "runtime"
```

**Comment by cgonyeo** [comment]
Should be fixed by https://github.com/appc/acpush/pull/2. Please reopen if you still have issues building.

**Comment by Andrei-Pozolotin** [comment]
works, thank you
https://aur.archlinux.org/packages/acpush/
